
#  Working with IDBac from Python


```{r eval=FALSE, include=FALSE}

library(reticulate)
#use_virtualenv("r-reticulate")
# create a new environment 
#reticulate::virtualenv_create("idbac")
# install pandas
conda_install("r-reticulate", "pandas")
conda_install("r-reticulate", "plotly")

conda_install("r-reticulate", "zstd")
reticulate::use_condaenv("r-reticulate")

reticulate::conda_install("r-reticulate","zstandard")

```



```{python}
import sqlite3
import json
import pandas as pd
import zstandard as zstd
```

```{python}
conn = sqlite3.connect('C:/Users/CMC/Documents/GitHub/programming_idbac/data/databases/my_new_database.sqlite')
print(conn)
```

```{python}
c = conn.cursor()
```

```{python}
t = ('172-1',)
c.execute('SELECT min_mass FROM spectra WHERE strain_id=?', t)
print(c.fetchall())

```




```{python}
t = ('172-1',)
c.execute('SELECT peak_matrix FROM spectra WHERE strain_id=?', t)
peaks = c.fetchone()
```

```{python}
print(type(peaks))
```



Get 172-1 sample peak lists as pandas df:
```{python}
df = pd.read_sql_query('SELECT peak_matrix FROM spectra WHERE strain_id=:spec', conn, params = {'spec':'172-1'})
js = df.iloc[0,0]
peaks = json.loads(js)
peaks = pd.DataFrame.from_dict(peaks)
print(peaks)
```



```{python}
sql = ('SELECT mass_index.mass_vector, spectra.spectrum_intensity '
       'FROM mass_index '
       'LEFT JOIN spectra '
       'ON mass_index.spectrum_mass_hash = spectra.spectrum_mass_hash '
       'WHERE strain_id=:spec '
       'AND max_mass > 6000 ')
       
       
       

       
       
       
       

df = pd.read_sql_query(sql, conn, params = {'spec':'172-1'})

```




```{python}
df
```

```{python}
js=df.iloc[0,1]


```



```{python}

dctx = zstd.ZstdDecompressor()
decompressed = dctx.decompress(js,len(js))

```






```{python include=FALSE}

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[1.5, 4.5],
    y=[0.75, 0.75],
    text=["Unfilled Rectangle", "Filled Rectangle"],
    mode="text",
))

for ind in a.index: 
  fig.add_shape(
          go.layout.Shape(
              type="rect",
              x0=a['mass'][ind] - 1,
              y0=0,
              x1=a['mass'][ind] + 1,
              y1=a['intensity'][ind],
              line=dict(
                  color="RoyalBlue",
                  width=2,
              ),
              fillcolor="LightSkyBlue",
          ))

fig.update_shapes(dict(xref='x', yref='y'))

py.plot(fig, filename = "data/python_output/2.html", auto_open=False)
```




```{r, echo=FALSE}
htmltools::includeHTML(here::here("data","python_output","2.html"))



```

